[[redirects]]
  from = "/services/*"
  to = "http://pktqvgj74h4g.cloud.wavemakeronline.com/Tutorial/services/*:splat"
  status = 200
  
## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/resources"
  to = "http://pktqvgj74h4g.cloud.wavemakeronline.com/Tutorial"
  status = 200
  