[[redirects]]
  from = "/services"
  to = "http://pktqvgj74h4g.cloud.wavemakeronline.com/Tutorial/"
  status = 404
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/resources"
  to = "http://pktqvgj74h4g.cloud.wavemakeronline.com/Tutorial/"
  status = 404
  force = true # COMMENT: ensure that we always redirect
