export const variables = {
    databaseVariable1: {
        _id: "wm-databaseVariable1-wm.LiveVariable-1624270394848",
        name: "databaseVariable1",
        owner: "Page",
        category: "wm.LiveVariable",
        dataBinding: [],
        operation: "read",
        dataSet: [],
        type: "Vacation",
        isList: false,
        saveInPhonegap: false,
        maxResults: 20,
        designMaxResults: 10,
        inFlightBehavior: "executeLast",
        startUpdate: true,
        autoUpdate: true,
        transformationRequired: false,
        liveSource: "hrdb",
        ignoreCase: true,
        matchMode: "startignorecase",
        orderBy: "id asc",
        propertiesMap: {
            columns: [
                {
                    fieldName: "employee",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "EMP_ID",
                    isPrimaryKey: false,
                    notNull: true,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: true,
                    relatedTableName: "EMPLOYEE",
                    relatedEntityName: "Employee",
                    relatedColumnName: "empId",
                    relatedFieldName: "employee.empId",
                    isList: false,
                    targetTable: "EMPLOYEE",
                    scale: 0,
                    columns: [
                        {
                            fieldName: "department",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "DEPT_ID",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: true,
                            relatedColumnName: "deptId",
                            targetTable: "DEPARTMENT",
                            scale: 0
                        },
                        {
                            fieldName: "employeeByManagerId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "MANAGER_ID",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: true,
                            relatedColumnName: "managerId",
                            targetTable: "EMPLOYEE",
                            scale: 0
                        },
                        {
                            fieldName: "empId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "EMP_ID",
                            isPrimaryKey: true,
                            notNull: true,
                            length: 255,
                            precision: 10,
                            generator: "identity",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "firstname",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "FIRSTNAME",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "lastname",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "LASTNAME",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "street",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "STREET",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "city",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "CITY",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "state",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "STATE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 2,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "zip",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "ZIP",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "birthdate",
                            type: "date",
                            fullyQualifiedType: "date",
                            columnName: "BIRTHDATE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 10,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "picurl",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "PICURL",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "jobTitle",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "JOB_TITLE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 40,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "username",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "USERNAME",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "password",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "PASSWORD",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "role",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "ROLE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "tenantId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "TENANT_ID",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        }
                    ]
                },
                {
                    fieldName: "id",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "ID",
                    isPrimaryKey: true,
                    notNull: true,
                    length: 255,
                    precision: 10,
                    generator: "identity",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "startDate",
                    type: "date",
                    fullyQualifiedType: "date",
                    columnName: "START_DATE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 10,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "endDate",
                    type: "date",
                    fullyQualifiedType: "date",
                    columnName: "END_DATE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 10,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "tenantId",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "TENANT_ID",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "status",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "STATUS",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "type",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "TYPE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                }
            ],
            entityName: "Vacation",
            fullyQualifiedName: "com.tutorial.hrdb.Vacation",
            tableType: "TABLE",
            primaryFields: ["id"]
        },
        bindCount: 13,
        tableName: "VACATION",
        tableType: "TABLE",
        properties: ["employee"],
        relatedTables: [
            {
                columnName: "employee",
                relationName: "employee",
                type: "Employee",
                watchOn: "HrdbEmployeeData",
                package: "com.tutorial.hrdb.Vacation"
            }
        ],
        filterFields: {},
        filterExpressions: {},
        package: "com.tutorial.hrdb.Vacation"
    },
    HrdbEmployeeData: {
        _id: "wm-HrdbEmployeeData-wm.LiveVariable-1624876076158",
        name: "HrdbEmployeeData",
        owner: "Page",
        category: "wm.LiveVariable",
        dataBinding: [],
        operation: "read",
        dataSet: [],
        type: "Employee",
        isList: true,
        saveInPhonegap: false,
        maxResults: 5,
        designMaxResults: 10,
        inFlightBehavior: "executeLast",
        startUpdate: true,
        autoUpdate: true,
        transformationRequired: false,
        liveSource: "hrdb",
        ignoreCase: true,
        matchMode: "startignorecase",
        orderBy: "empId asc",
        propertiesMap: {
            columns: [
                {
                    fieldName: "department",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "DEPT_ID",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: true,
                    relatedTableName: "DEPARTMENT",
                    relatedEntityName: "Department",
                    relatedColumnName: "deptId",
                    relatedFieldName: "department.deptId",
                    isList: false,
                    targetTable: "DEPARTMENT",
                    scale: 0,
                    columns: [
                        {
                            fieldName: "deptId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "DEPT_ID",
                            isPrimaryKey: true,
                            notNull: true,
                            length: 255,
                            precision: 10,
                            generator: "identity",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "name",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "NAME",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "budget",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "BUDGET",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "q1",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "Q1",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "q2",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "Q2",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "q3",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "Q3",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "q4",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "Q4",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "deptCode",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "DEPT_CODE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 20,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "location",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "LOCATION",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "tenantId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "TENANT_ID",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        }
                    ]
                },
                {
                    fieldName: "employeeByManagerId",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "MANAGER_ID",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: true,
                    relatedTableName: "EMPLOYEE",
                    relatedEntityName: "Employee",
                    relatedColumnName: "managerId",
                    relatedFieldName: "employeeByManagerId.empId",
                    isList: false,
                    targetTable: "EMPLOYEE",
                    scale: 0,
                    columns: [
                        {
                            fieldName: "department",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "DEPT_ID",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: true,
                            relatedTableName: "DEPARTMENT",
                            relatedEntityName: "Department",
                            relatedColumnName: "deptId",
                            relatedFieldName: "department.deptId",
                            isList: false,
                            targetTable: "DEPARTMENT",
                            scale: 0,
                            columns: [
                                {
                                    fieldName: "deptId",
                                    type: "integer",
                                    fullyQualifiedType: "integer",
                                    columnName: "DEPT_ID",
                                    isPrimaryKey: true,
                                    notNull: true,
                                    length: 255,
                                    precision: 10,
                                    generator: "identity",
                                    isRelated: false,
                                    scale: 0
                                },
                                {
                                    fieldName: "name",
                                    type: "string",
                                    fullyQualifiedType: "string",
                                    columnName: "NAME",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 19,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 2
                                },
                                {
                                    fieldName: "budget",
                                    type: "integer",
                                    fullyQualifiedType: "integer",
                                    columnName: "BUDGET",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 10,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 0
                                },
                                {
                                    fieldName: "q1",
                                    type: "integer",
                                    fullyQualifiedType: "integer",
                                    columnName: "Q1",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 10,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 0
                                },
                                {
                                    fieldName: "q2",
                                    type: "integer",
                                    fullyQualifiedType: "integer",
                                    columnName: "Q2",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 10,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 0
                                },
                                {
                                    fieldName: "q3",
                                    type: "integer",
                                    fullyQualifiedType: "integer",
                                    columnName: "Q3",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 10,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 0
                                },
                                {
                                    fieldName: "q4",
                                    type: "integer",
                                    fullyQualifiedType: "integer",
                                    columnName: "Q4",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 10,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 0
                                },
                                {
                                    fieldName: "deptCode",
                                    type: "string",
                                    fullyQualifiedType: "string",
                                    columnName: "DEPT_CODE",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 20,
                                    precision: 19,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 2
                                },
                                {
                                    fieldName: "location",
                                    type: "string",
                                    fullyQualifiedType: "string",
                                    columnName: "LOCATION",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 19,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 2
                                },
                                {
                                    fieldName: "tenantId",
                                    type: "integer",
                                    fullyQualifiedType: "integer",
                                    columnName: "TENANT_ID",
                                    isPrimaryKey: false,
                                    notNull: false,
                                    length: 255,
                                    precision: 10,
                                    generator: "assigned",
                                    isRelated: false,
                                    scale: 0
                                }
                            ]
                        },
                        {
                            fieldName: "employeeByManagerId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "MANAGER_ID",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: true,
                            relatedTableName: "EMPLOYEE",
                            relatedEntityName: "Employee",
                            relatedColumnName: "managerId",
                            targetTable: "EMPLOYEE",
                            scale: 0
                        },
                        {
                            fieldName: "empId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "EMP_ID",
                            isPrimaryKey: true,
                            notNull: true,
                            length: 255,
                            precision: 10,
                            generator: "identity",
                            isRelated: false,
                            scale: 0
                        },
                        {
                            fieldName: "firstname",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "FIRSTNAME",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "lastname",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "LASTNAME",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "street",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "STREET",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "city",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "CITY",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "state",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "STATE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 2,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "zip",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "ZIP",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "birthdate",
                            type: "date",
                            fullyQualifiedType: "date",
                            columnName: "BIRTHDATE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 10,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "picurl",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "PICURL",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "jobTitle",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "JOB_TITLE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 40,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "username",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "USERNAME",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "password",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "PASSWORD",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "role",
                            type: "string",
                            fullyQualifiedType: "string",
                            columnName: "ROLE",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 19,
                            generator: "assigned",
                            isRelated: false,
                            scale: 2
                        },
                        {
                            fieldName: "tenantId",
                            type: "integer",
                            fullyQualifiedType: "integer",
                            columnName: "TENANT_ID",
                            isPrimaryKey: false,
                            notNull: false,
                            length: 255,
                            precision: 10,
                            generator: "assigned",
                            isRelated: false,
                            scale: 0
                        }
                    ]
                },
                {
                    fieldName: "empId",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "EMP_ID",
                    isPrimaryKey: true,
                    notNull: true,
                    length: 255,
                    precision: 10,
                    generator: "identity",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "firstname",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "FIRSTNAME",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "lastname",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "LASTNAME",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "street",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "STREET",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "city",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "CITY",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "state",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "STATE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 2,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "zip",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "ZIP",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "birthdate",
                    type: "date",
                    fullyQualifiedType: "date",
                    columnName: "BIRTHDATE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 10,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "picurl",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "PICURL",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "jobTitle",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "JOB_TITLE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 40,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "username",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "USERNAME",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "password",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "PASSWORD",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "role",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "ROLE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "tenantId",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "TENANT_ID",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                }
            ],
            entityName: "Employee",
            fullyQualifiedName: "com.tutorial.hrdb.Employee",
            tableType: "TABLE",
            primaryFields: ["empId"]
        },
        isDefault: true,
        bindCount: 1,
        tableName: "EMPLOYEE",
        tableType: "TABLE",
        properties: ["department", "employeeByManagerId"],
        relatedTables: [
            {
                columnName: "department",
                relationName: "department",
                type: "Department",
                watchOn: "HrdbDepartmentData",
                package: "com.tutorial.hrdb.Employee"
            },
            {
                columnName: "employeeByManagerId",
                relationName: "employeeByManagerId",
                type: "Employee",
                watchOn: "HrdbEmployeeData",
                package: "com.tutorial.hrdb.Employee"
            }
        ],
        filterExpressions: {},
        package: "com.tutorial.hrdb.Employee"
    },
    serviceVariable1: {
        _id: "wm-serviceVariable1-wm.ServiceVariable-1624270968725",
        name: "serviceVariable1",
        owner: "Page",
        category: "wm.ServiceVariable",
        dataBinding: [],
        type: "integer",
        service: "hrdb",
        operation: "countVacations",
        operationId: "VacationController_countVacations",
        operationType: "get",
        serviceType: "DataService",
        dataSet: [],
        isList: false,
        maxResults: 20,
        startUpdate: false,
        autoUpdate: true,
        inFlightBehavior: "executeLast",
        transformationRequired: false,
        saveInPhonegap: false,
        controller: "Vacation"
    }
}

export const getVariables = () => JSON.parse(JSON.stringify(variables))
